name: Download Container Workspaces

on:
  # schedule:
  #   - cron:  '0 * * * *'
  workflow_dispatch:

jobs:
  download-container:
    runs-on: ubuntu-latest
    env:
      ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
      CONTAINER_ID: ${{ secrets.CONTAINER_ID }}
      USER_EMAIL: ${{ secrets.USER_EMAIL }}
      USER_NAME: ${{ secrets.USER_NAME }}
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Set up Google Cloud credentials
        run: echo "$GCP_SA_KEY" > ./gcp-sa-key.json

      - name: Download container
        run: node ./scripts/downloadContainer.js

      - name: Extract workspace info and set as env variable
        run: |
          echo "WORKSPACES_INFO=$(jq -r '.workspace[] | "\(.name): \(.description)"' workspaces/workspaces.json | tr '\n' ', ')" >> $GITHUB_ENV

      - name: Commit and push changes
        run: |
          git config --local user.email "${{ env.USER_EMAIL }}"
          git config --local user.name "${{ env.USER_NAME }}"
          git add -A workspaces/
          git diff --quiet && git diff --staged --quiet || (git commit -m "Download all container workspace data: ${{ env.WORKSPACES_INFO }}" -a && git push)
