name: Run uploadChanges on PR merge to master

on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  uploadChanges:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Dependencies
        run: npm ci

      - name: Run uploadChanges script
        run: node scripts/uploadChanges.js
