name: Upload changes to container

on:
  pull_request:
    types:
      - closed
    branches:
      - master
  workflow_dispatch:

jobs:
  uploadChanges:
    if: (github.event_name == 'pull_request' && github.event.pull_request.merged == true) || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    env:
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Dependencies
        run: npm ci

      - name: Set up Google Cloud credentials
        run: echo "$GCP_SA_KEY" > ./gcp-sa-key.json

      - name: Run uploadChanges script
        run: node scripts/uploadChanges.js
